### ISSUE TITLE
ios_facts legacy/base fails to gather interface facts when device has deleted interface

### ISSUE THREAD

**Issue by gawul** [ansible-collections/cisco.ios#879]
##### SUMMARY
ios_facts legacy/base fails to gather interface facts when IOS-XE device running 17.9.3 has a deleted interface

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/module_utils/network/ios/facts/legacy/base.py

##### ANSIBLE VERSION

N/A

##### COLLECTION VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

IOS-XE 17.9.3 (confirmed on Cat9500 and ISR4431) does exhibit the behavior triggering the KeyError

Appears to be a change in behavior in IOS-XE and I'll open a TAC case to follow-up with Cisco from that side as well
17.6.3 does not exhibit this (both `show interface` and `show ip interface` list out the deleted interfaces)

##### STEPS TO REPRODUCE

gather ios_facts on an IOS-XE device running 17.9.3 with a deleted interface

The base.py function `populate_ipv4_interfaces` iterates through the output of `show ip interface` expecting all keys found to be also present in `show interface` that was used in function `populate_interfaces` however that is not true when the device has a deleted interface.  The output of `show ip interface` will contain the deleted interface whereas the `show interface` does not in IOS-XE version 17.9.3.

##### EXPECTED RESULTS

Interface facts to be gathered even if there is a discrepancy between device output (safely reference keys)

##### ACTUAL RESULTS

KeyError in populate_ipv4_interfaces referencing the deleted interface

**Comment by KB-perByte** [comment]
Hey @gawul, would you please share some details from the appliance? of the commands mentioned?
We can check the failure with that.

Regards.

**Comment by gawul** [comment]
On the router running ios > 17.9.3, create and then delete a sub-interface.  When running `show interfaces`  the deleted sub-interface is not listed.  However when running `show ip interface` that interface is listed in a state of deleted

Simple play to pull in ios_facts from device router.  Module fails when `populate_ipv4_interfaces` tries to reference the key of the deleted interface name that was not populated when the `populate_interfaces` function created the keys based off `show interfaces`

[ansibleplay.txt](https://github.com/ansible-collections/cisco.ios/files/12767632/ansibleplay.txt)
[router.txt](https://github.com/ansible-collections/cisco.ios/files/12767633/router.txt)

**Comment by gawul** [comment]
Cisco TAC did acknowledge the inconsistency in their output, but the ansible module should not make assumptions that it would be consistent.

https://bst.cloudapps.cisco.com/bugsearch/bug/CSCwf95506

**Comment by gawul** [comment]
@KB-perByte is there further detail you are looking for on this?

**Comment by roverflow** [comment]
@gawul I will be looking at this issue, will post some updates soon

**Comment by PcInfamy** [comment]
Also experiencing this

**Comment by zendritic** [comment]
Another instance where assuming the output of one command can be used as keys in a dict created from the output of another command:

Some IOS routers dynamically create interfaces called "MPLS-SR-Tunnel<number>" when an SR link drops. Then they are destroyed. If this happens between when ansible runs "show interfaces" and "show ip interface", it results in the same key error. Any other situation where an interface happens to be created between when ansible runs "show interfaces" and "show ip interface" will result in this key error. The code should check if the key exists before attempting to use the parsed interface name as a key, and handle that, possibly by adding that key to the dict, instead of failing the play.

**Comment by roverflow** [comment]
@gawul Thanks for reporting the issue.After  testing across various versions, it appears that the issue is not consistently present in all versions, Therefore, it would be a no fix since its a issue on cisco's end. Do let me know  If you do have any further questions or concerns, please feel free to let me know. Thanks
